---
k3s_cluster:
  children:
    server: 
      hosts: 
        vps-k3s-cp-01:
          ansible_host: 51.255.44.182
          tailscale_ip: 100.64.20.1
        vps-k3s-cp-02:
          ansible_host: 51.38.176.25
          tailscale_ip: 100.64.20.2
    agent:
      hosts:
        vps-k3s-worker-01:
          ansible_host: 51.255.35.139
          tailscale_ip: 100.64.20.11
  vars:
    k3s_version: v1.36.4+k3s1
    api_endpoint: "vps-k3s-cp-01.taila84b44.ts.net"

    # Optional vars
    extra_server_args: "--node-name={{ inventory_hostname }}.taila84b44.ts.net --node-ip={{ tailscale_ip }} --node-external-ip={{ tailscale_ip }} --flannel-backend=none --disable-network-policy --disable kube-proxy"
    extra_agent_args: "--node-name={{ inventory_hostname }}.taila84b44.ts.net --node-ip={{ tailscale_ip }} --node-external-ip={{ tailscale_ip }}"
    cluster_context: vps-k3s

all: 
  vars: 
    ansible_user: debian
    ansible_python_interpreter: /usr/bin/python3