---
k3s_cluster:
  children:
    server: 
      hosts: 
        51.255.44.182:
        51.38.176.25:
    agent:
      hosts:
        51.255.35.139

all: 
  vars: 
    ansible_user: debian
    ansible_python_interpreter: /usr/bin/python3