- name: OS Bootstrap
  hosts: k3s_cluster
  gather_facts: true
  become: true
  
  tasks:
    - name: Disable swap
      command: swapoff -a
      when: ansible_facts["swaptotal_mb"] > 0
      changed_when: true

    - name: Remove swap entry from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#\s]+\s+[^#\s]+\s+swap\s+.*)$'
        replace: '# \1'