---
- name: System Requirements
  import_playbook: playbooks/sysreq.yml

- name: Tailscale Mesh Setup
  import_playbook: playbooks/tailscale.yml

- name: K3s Cluster Bootstrap
  import_playbook: k3s.orchestration.site
